Support `style` attribute
dioxus-community/dioxus-free-icons pull request #54
Opened 2024-08-07 02:50 UTC by wooden-worm

Fixes https://github.com/dioxus-community/dioxus-free-icons/issues/53

2024-08-07 18:48 UTC, marc2332 requested changes

2024-08-07 18:48 UTC, marc2332 commented on packages/lib/src/icon_component.rs
> +    }
It is unnecessary to duplicate that much code, just do something like:
```suggestion
    rsx!(
        svg {
            class: "{props.class}",
            style: props.style,
            height: "{props.height}",
            width: "{props.width}",
            view_box: "{props.icon.view_box()}",
            xmlns: "{props.icon.xmlns()}",
            xmlns: "{props.icon.xmlns()}",
            fill,
            stroke,
            stroke_width,
            stroke_linecap: "{props.icon.stroke_linecap()}",
            stroke_linejoin: "{props.icon.stroke_linejoin()}",
            if let Some(title_text) = props.title {
                title {
                    "{title_text}"
                }
            },
            {props.icon.child_elements()}
        }
    )
```

2024-08-24 18:22 UTC, wooden-worm commented
@marc2332 is there anything else needed to merge this PR?

2024-08-24 18:58 UTC, marc2332 commented
> @marc2332 is there anything else needed to merge this PR?

hey! Sorry, I missed this as I wasn't requested as reviewer again

2024-08-24 18:58 UTC, marc2332 approved these changes

2024-08-24 19:30 UTC, merged